- Jenkinsfile
- openshift/configmap-template.yaml
- openshift/manual-graph-sync-job.yaml
- openshift/template.yaml
- playbooks/provision.yaml
- manual-graph-sync-batchjob added
- KUBERNETES_VERIFY_TLS hardcoded to 0
- removed user-api BuildConfig as it is part of its own repo/pipeline
- renamed THOTH_CEPH_HOST to THOTH_S3_ENDPOINT_URL
- removed repository name from image of cronjobs
> Some more cleanups for the CI/CD pipeline

- Pipfile
- Pipfile.lock
- features/analyse_container_image.feature
- features/environment.py
- features/result_api.feature
- features/steps/result_api_steps.py
- features/steps/user_api_steps.py
- openshift/buildConfig-e2e-test-template.yaml
- tox.ini
This is the first iteration of End-to-End Tests, I cover reading the Result API. Tests use [Behave](http://behave.readthedocs.io/en/stable/index.html) and [Hamcrest](http://pyhamcrest.readthedocs.io/en/latest/tutorial/)
A BuildConfig for a container running the test is included, that container could be started via `oc delete pod core-e2e-test && oc run -ti core-e2e-test --image=core-e2e-test --restart=Never -- /opt/app-root/bin/behave --no-color`
Open Question: How to make this part of the CI?
> Feature: End-to-End Tests

- bots/Pipfile
- bots/Pipfile.lock
- bots/daily_standup.py
- playbooks/provision.yaml
- playbooks/roles/thoth-core/tasks/main.yaml
the playbooks require Ansible role thoth-station.thoth-core-imagestreams >=0.2.0 now, it is hosted on Ansible Galaxy
> ansible cleanup imagestreams

- .travis.yml
- bots/config.yaml
I am testing Zuul gating on the kebechet repository, so I dont want sesheta to interfere with that.
> sesheta is no longer merging on kebechet repository

- .git_init/hooks/pre-commit
- .git_init/hooks/pre-push
- git-clone-repos.yaml
Added functionalities:
1. pipenv installing all the dependencies in all the repositories. (optionally feature,can be un-set by NO_PIPENV_SETUP=1) 
2. Update git hooks functionality as optional, it can be un-set by NO_GIT_HOOKS=1
3. A user can specify the git hooks repository ( which repository the user has the git hooks ".git_init/hooks") by setting the variable GIT_HOOKS_REPO(default=core)
4. Updated TOKEN-> GITHUB_TOKEN, USERS-> GITHUB_USER
5. Also added custom git hooks ".git_init/hooks" in the PR 
Review needed in Blog:
https://mojo.redhat.com/groups/red-hat-artificial-intelligence-center-of-excellence-ai-coe/projects/thoth/blog/2018/07/02/thoth-station-set-up
Made an attempt :see_no_evil: 
Question:
1. If a  user doesn't have "pipenv" installed in the system, then the scripts is …
> updated the ansible-playbook functionality

- README.rst
- docs/adr/0000-use-markdown-architectural-decision-records.md
- docs/adr/0001-use-gpl3-as-license.md
- docs/adr/template.md
Using ADR to document architectural decisions, first two on using ADR and GPL are done.
> using Markdown Architectural Decision Records

- community/generator/sig_readme.tmpl
- community/generator/ug_readme.tmpl
- community/generator/wg_readme.tmpl
- community/sig-docs/README.md
- community/sig-observability/README.md
- community/sig-pipelines/README.md
Refactoring #348 (part 2/4)
This removes the references to Slack and Mailing Lists from the SIG documentation, as they are currently empty and unused.
It also makes these optional in the templates.
> Remove empty references to Slack and Mailing lists

- community/sig-list.md
- community/sig-observability/README.md
- community/sigs.yaml
Setup a dedicated meetup slot for Thoth observability
This would create a dedicated time slot in the thoth-station community to have a discussion regarding metrics and performance.
> Setup a dedicated meetup slot for Thoth observability

- README.rst
- community/Makefile
- community/README.md
Add some basic documentation about `labels.yaml`, `sigs.yaml` and `github-config.yaml` and how to maintain them.
It adds a command to run the label doc generator app.
Also, it replaces `docker` with `podman`.
> Add documentation about labels/sig/repo maintenance

- community/github-config.yaml
Include new repos in thoth-station and remove old team members
Firstly, Thanks for all the contributions for the member of the thoth-station, who are no longer part of this.
1. Fix the membership: ![team-members](https://user-images.githubusercontent.com/14028058/153498532-610239bf-8d19-48af-9e54-6441962083b9.png)
- Removed a few of the old team members from org, they would still be able to contribute as open-source contributors.
- Removed some team members who are part of Open Services Group, however haven't accepted the thoth-station invite for more than a month. Taking as they would like to stay open source contributor instead of the team member of thoth-station.
2. Added the repo which were not tracked in here.
> Include new repos in thoth-station and remove old team members

- community/sig-devsecops/README.md
- community/sig-list.md
- community/sigs.yaml
We switched the SP-Pipelines meeting to a weekly cadence for the time being.
This PR is to update the SIG documentation accordingly - just that change from bi-weekly to weekly.
> Set SP-pipelines meeting to weekly

- .prow.yaml
Fixes: #406
- No
Add a `--github-endpoint` to *peribolos* and *label_sync* prow jobs so that they use the local `ghproxy` instance.
See https://github.com/kubernetes/test-infra/tree/master/ghproxy#ghproxy
> Make peribolos and label_sync use ghproxy

- .prow.yaml
- community/labels.yaml
Follow-up after #407
- No
Use `--github-token-path` instead of `--token` as an argument for `label_sync`.
After adding the `--github-*` parameters to use *ghproxy* in #407, `label_sync` is not running, complaining about:
``` json
+ /ko-app/label_sync '--github-endpoint=http://ghproxy' '--github-endpoint=https://api.github.com' '--config=community/labels.yaml' '--orgs=thoth-station' '--token=/etc/github/oauth' --confirm
{"component":"label_sync","file":"k8s.io/test-infra/label_sync/main.go:178","func":"main.gatherOptions","level":"fatal","msg":"deprecated GitHub options, include --endpoint, --graphql-endpoint, --token, --tokens, --token-burst cannot be combined with new --github-XXX counterparts","severity":"fatal","time":"2022-05-10T11:11:17Z"}
```
> [prow] Fix label_sync token argument name

- docs/adr/0005-obtimizing-keb-runs.md
https://github.com/thoth-station/kebechet/issues/873
- No
> ADR for kebechet optimization

- OWNERS
- community/github-config.yaml
HouseKeeping: Updated repos and teams for triaging
- Updated the missing repos in the listed.
- keep the honourary members are members and removed from teams.
- Allowed all public repo in thoth-station for triage for dev team
- Removed redundant teams
> HouseKeeping: Updated repos and teams for triaging

- community/github-config.yaml
Related to https://github.com/thoth-station/srcops-testing/issues/265#issuecomment-1168633204
and https://github.com/thoth-station/mi/issues/589
- No
Enable projects feature for `thoth-station/support` repository, so that we can collect project-related events through the Github Issue Events API
> Enable projects for thoth-station/support && thoth-station/srcops-testing

- OWNERS_ALIASES
- community/sig-devsecops/README.md
- community/sig-list.md
- community/sig-observability/README.md
- community/sig-user-experience/README.md
- community/sigs.yaml
Note that this PR includes the commit from #421. It is expected to merge after that other (simpler) update.
- No
Update SIG information for DevSecOps and Observability.
On one hand, this updates information about current meetings and members of the team.
Also, in the SIG-DevSecOps meeting on 2022-07-07 there was a review of the repos associated with SIG-DevSecOps, and this PR adds the updated list of repos for the SIG.
The sub-projects where repos belong also are updated to reflect the grouping.
> Update SIG DevSecOps and Observability metadata

- community/github-config.yaml
Include @MichaelClifford in the team to maintain repos
Related-to: https://github.com/thoth-station/ray-ml-worker/pull/30
> Include @MichaelClifford in the team to maintain repos

- community/github-config.yaml
- No
This updates the list of repos to which the `SigChairs` team has _write_ access to so that it matches the list of repos that have _triage_ access for org members.
I realize that some of the repos added to the list are actually archived. I could go one by one and filter out, but I thought it was simpler to just keep both list of repos in sync.
The trigger for this proposed change was the missing write access to one of these repos in particular: `opendatahub-cnbi`. Strictly, this is the only one needed right now that I'm aware of, but again I thought it would be better to keep both lists in sync.
> Give SigChairs write perms on all repos

- community/github-config.yaml
Allow admins to write privileges on odh-dashboard repo
> Allow admins to write privileges on odh-dashboard repo

- community/SUPPORT_POLICY.md
:sparkles: add a short note on how we choose supported runtime environments
closes #466 
> add support policy document
