.gitignore
openshift/deploy.sh

Download janusgraph template on deployment

---

Jenkinsfile
openshift/configmap-template.yaml

fixing typos

---

openshift/configmap-template.yaml
openshift/template.yaml
playbooks/roles/provision-thoth-core/tasks/main.yaml
playbooks/roles/validate-thoth-core/tasks/main.yaml

synchronizing to incorporate https://github.com/thoth-station/result-api/pull/1

---

bots/CHANGELOG.md
bots/Pipfile
bots/Pipfile.lock
bots/README.md
bots/approve.py
bots/check_if_labels_present.py
bots/config.yaml
bots/merge_pr.py
bots/openshift/buildConfig-template.yaml
bots/openshift/cronJob-template.yaml
bots/playbooks/deploy-sesheta-cronjobs.yaml
bots/playbooks/roles/sesheta-cronjob/tasks/main.yaml
bots/sesheta/__init__.py
bots/sesheta/common.py
doc/release-management.md

**approve.py** now checks if all commits have successful CI status, CI context used is 'continuous-integration/jenkins/pr-merge'.
if 'needs-rebase' label is present, but GitHub thinks the PR is mergable, the label is removed.
'work-in-progress' label is a NOGO: the PR will be left alone.
**merge_pr.py** will merge any PR that has the 'approved' label, if one of 'needs-rebase' or 'work-in-progress' label is present, it will take precedence and no merge will happen.
**check_if_labels_present.py** will make sure that the labels we depend on are present.
**config.yaml** is selfexplanatory ;)

This is the Cyborg Team Members

---

doc/naming-schema.md

added based on a conversation on mattermost

---

playbooks/provision.yaml
playbooks/roles/thoth-backend/tasks/main.yaml
playbooks/roles/thoth-core-imagestreams/tasks/main.yaml

added a role to import required imagestreams, so that buildconfig can use them later on
used by solver BuildConfig

added a role to import required imagestreams

---

doc/development-good-practice.md

Part of https://trello.com/c/MFUhenl8/200-create-git-hooks-for-automatic-code-checks

documentation of git hooks

---

playbooks/roles/thoth-middletier/tasks/main.yaml

Depends-On: https://github.com/thoth-station/solver/pull/49
Depends-On: https://github.com/thoth-station/package-extract/pull/92

Add solver and package extract pod templates

---

doc/code-review.md

added a chapter about code review and merges

---

openshift/secret-template.yaml

Signed-off-by: Christoph Görn <goern@b4mad.net>

added management api key

---

openshift/manual-graph-sync-job.yaml

Signed-off-by: Marek Cermak <macermak@redhat.com>
modified:   openshift/manual-graph-sync-job.yaml

Update janusgraph environment variables

---

Pipfile
Pipfile.lock

addressing CVEs and relocked

---

bots/Pipfile
bots/Pipfile.lock

addressing CVE-2017-18342 and CVE-2018-18074

---

playbooks/provision.yaml

create the BC and IS correctly

---

git-clone-repos.yaml

Incrase Pagination to have all repositories cloned for thoth-station

---

openshift/configmap-template.yaml
playbooks/provision.yaml

Depends-On: https://github.com/thoth-station/adviser/pull/191

State Isis API URL

---

openshift/configmap-template.yaml

fixed the ISIS_API_URL parameter name

---

openshift/configmap-template.yaml

[WIP] added ConfigMap entries required for Dgraph

---

openshift/configmap-template.yaml

* use dashes
* TLS path is not generic enough to have it in CM

Dgraph configuration adjustments

---

requirements.yaml

Removed janusgraph service

---

openshift/configmap-template.yaml

Fixes https://github.com/thoth-station/core/issues/223

Renamed sentry-environment to sentry-dsn

---

openshift/configmap-template.yaml

Depends-On: https://github.com/thoth-station/core/pull/224

Remove cleanup time

---

doc/repository_directory_layout.rst

initial draft for directory layout

---

doc/ROADMAP.md

added a high level roadmap document

---

RELEASES.md

added release notes for 2020.09.17

---

RELEASES.md

added release notes for 2020.09.30

---

RELEASES.md

this closes https://github.com/thoth-station/investigator/issues/294 https://github.com/thoth-station/adviser/issues/1178 https://github.com/thoth-station/core/issues/236 

added 2020.10.27 release notes

---

docs/adr/0002-release-policy.md

add ADR documenting our release policy

add release policy ADR

---

docs/ROADMAP.md

add section on nb-reqs to ROADMAP document

---

docs/ROADMAP.md

Improve doc on Jupyter tools

---

README.rst
docs/adr/0003-gitops-repo-url-in-thoth-yaml.md

[WIP] add ADR on changing .thoth.yaml

---

RELEASES.md

20201201 release note

---

RELEASES.md

Release 2021.02.01

---

CONTRIBUTING.md

basically ported it from the template project

add a contributing doc

---

docs/intern-projects/Inferring-package-names-out-of-Python-imports.md
docs/intern-projects/classify-errors-produced-during-installation-of-python-modules.md

Add solver classifier intern project description

---

.github/ISSUE_TEMPLATE/membership.md
.github/ISSUE_TEMPLATE/repo-archive.md
.github/ISSUE_TEMPLATE/repo-create.md
community/labels.md
docs/adr/0004-naming-convention-images.md

Introduce ADR for naming convention of images

---

community/github-config.yaml

add ps-nlp and ps-cv

---

README.rst

Add refs to ADR

---

community/github-config.yaml
community/labels.yaml

add support repo and a few labels for it

---

community/github-config.yaml

fix some prescriptions related configs

---

.github/ISSUE_TEMPLATE/.config.yml
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/major-release.md
.github/ISSUE_TEMPLATE/minor-release.md
.github/ISSUE_TEMPLATE/patch-release.md
.github/ISSUE_TEMPLATE/redeliver_container_image.md
.github/PULL_REQUEST_TEMPLATE.md
community/github-config.yaml

- :sparkles: add srcops-notify-bot repo
- :sparkles: add moldavite configs

add moldavite api

---

community/github-config.yaml

I added the ray repos, @harshad16 @erikerlandson please add a description to them.

add the ray repos :sparkles:

---

community/github-config.yaml

Create new repo for ps image processing

---

community/github-config.yaml

add prescriptions-refresh-job

---

community/github-config.yaml

add Pep as a Dev

---

docs/intern-projects/generate-prescription-from-text.md

add text2prescription intern project

---

community/generator/app.go
community/generator/app_test.go

Refactoring #348 (part 1/4)
Update the generator app to current code from upstream.
Code from [kubernetes/community at 0aba75023694cf499bf70e32ed52a4a1679252f6.](https://github.com/kubernetes/community/blob/97dd8458700e2fcc2d06cf0ff204e5c117ee503b/generator/app.go)

Update the generator app

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md

- No
Some formatting changes to the GitHub issue and templates for the repo, aiming at improved usability.
I was finding myself editing a bit too much of the templates when creating an issue or PR.
This is an attempt to make them more friendly.

Make GitHub issue templates a bit more friendly

---

community/github-config.yaml

Fixes: https://github.com/thoth-station/stress-tests/issues/2
- No

Add stress-tests repo to github config

---

community/github-config.yaml

Include pulp metrics exporter

---

community/sig-observability/README.md

Add mi to the subprojects

---

community/Makefile
community/README.md

Differentiate between files generation and label sync in Makefile

---

community/sig-list.md
community/sig-stack-guidance/README.md
community/sigs.yaml

Add regular SIG Stack Guidance meeting

---

community/github-config.yaml

Remove user from devs team

---

docs/adr/0005-automatically-bump-container-image-versions.md

Related to https://github.com/thoth-station/kebechet/issues/991
- No
Introduce an ADR to discuss about solutions for automatic updates of base image versions used to deliver container images.

Introduce an ADR for automatic base image version updates

---

community/github-config.yaml

resolves https://github.com/thoth-station/support/issues/203
- No
SSIA

added oindrillac to thoth members

---

community/github-config.yaml

This is so issues/cards can be assigned to us
- No
Add me (@4n4nd) and @Shreyanand to the thoth-station org

Add @4n4nd and @Shreyanand as thoth-station org members

---

docs/ROADMAP.md
docs/TermsAndConditionsForTheScrum.md

Fixes: https://github.com/open-services-group/community/issues/143
Update the Terms&Conditions for the Scrum document:
Changes include:
- More structure/sections in the document.
- Dedicated section for issue quality
- Add references to the SIGs
- Add effort estimates
- Switch from 2-week to 3-week sprints
Also updating the roadmap document to fix links to projects.

Update the Terms and Conditions for the Scrum document

---

community/github-config.yaml

removing pacospace :(

---

community/github-config.yaml

Signed-off-by: Shreekar <sshreeka@redhat.com>
- Yes
- No

Add shreekarSS to thoth members

---

OWNERS_ALIASES
community/sig-list.md
community/sig-user-experience/README.md
community/sigs.yaml

Updated chair/tech lead and weekly meeting details
- No
Updating the metadata about SIG User Experience:
- Change from @pacospace (thanks! :wave:) to @Gkrumbach07
- Add details about the weekly meeting

Update SIG-UserExperience details

---

community/github-config.yaml

Related to https://github.com/thoth-station/core/issues/419 and https://github.com/thoth-station/mi/issues/589
and https://github.com/thoth-station/srcops-testing/issues/265
(needs testing to be closed)
- No
SSIA

Enable repository projects for thoth-station organisation

---

community/github-config.yaml

Allow sig-chairs with write access to multiple repos
Fixes: https://github.com/thoth-station/core/issues/427

:turtle: Allow sig-chairs with write access to multiple repos

---

community/github-config.yaml

Thank you for your service
we would keep our colleagues on the OWNERS list from here on forth.
Removing from config to relieve them from notifications. 
Thank you for the service.

:pray: Thank you for your service

---

docs/code-review.rst

Update ci and code review docs

---

.pre-commit-config.yaml
OWNERS_ALIASES
community/sig-list.md
community/sig-stack-guidance/README.md
community/sigs.yaml

- 🙏 thanks for all the work @fridex!!
- :arrow_up: pre-commit plugins

sig yaml cleanup

---

community/labels.yaml

this should have the fortunate side-effect of fixing #459

Fix label description typo.

---

community/github-config.yaml

Include the repos missing from the github config

Include the repos missing from the github config

---

docs/TermsAndConditionsForTheScrum.md

Closes #455
Should I add some examples for what should be `kind/bug` or not ?
Also, what how do we qualify stuff which is broken but "not problematic enough"
? `kind/cleanup` ? Hypothetical `kind/enhancement` ?
/hold

Add explanation of the zero-bug policy

---

community/OWNERS
community/labels.yaml

rename CNBi->CRE, add TRaaS

---

community/labels.md

#472 updated `labels.yaml` but we forgot to sync `labels.md` accordingly
- No
``` shell
podman run --rm -v ./:/community:z \
gcr.io/k8s-prow/label_sync:latest --action docs \
--config /community/labels.yaml   --docs-template /community/labels.md.tmpl \
--docs-output /community/labels.md
```
(from the `label-sync` make target)

Sync labels.md after recent labels.yaml change

---

community/github-config.yaml

This PR is to move myself from member to admin of the thot-station GitHub org.

Make myself an org admin

---

.pre-commit-config.yaml
OWNERS
OWNERS_ALIASES
community/OWNERS
community/README.md
community/github-config.yaml
community/sig-devsecops/README.md
community/sig-list.md
community/sig-observability/README.md
community/sig-stack-guidance/README.md
community/sig-user-experience/README.md
community/sigs.yaml
community/wg-cnbi/README.md

- put a hibernation notice on the sigs, remove the meeting data
- :arrow_up: update pre-commit config

hibernate sigs
